import {
  FilterEl1,
  FilterEl2,
  FilterEl3,
  FilterEl4,
  FilterEl5,
  FilterEl6,
} from "./icons";

export const categories = [
  { _id: "1", category: "Shtëpi me qera", icon: `${FilterEl1}` },
  { _id: "2", category: "Prona imobilare", icon: `${FilterEl2}` },
  { _id: "3", category: "Ambiente biznesi me qera", icon: `${FilterEl3}` },
  { _id: "4", category: "Ambiente biznesi në shitje", icon: `${FilterEl4}` },
  { _id: "5", category: "Truall ose tokë", icon: `${FilterEl5}` },
  { _id: "6", category: "Kërkesa për shtëpi", icon: `${FilterEl6}` },
];
export const countries = [
  { _id: "1", country: "Shqiperi" },
  { _id: "2", country: "Kosove" },
  { country: "Maqedoni", _id: "3" },
];
export const cities = [
  { _id: "1", city: "Tiranë", countryId: "1" },
  { _id: "2", city: "Durrës", countryId: "1" },
  { _id: "3", city: "Shkodra", countryId: "1" },
  { _id: "4", city: "Elbasani", countryId: "1" },
  { _id: "5", city: "Vlora", countryId: "1" },
  { _id: "6", city: "Korça", countryId: "1" },
  { _id: "7", city: "Fieri", countryId: "1" },
  { _id: "8", city: "Berati", countryId: "1" },
  { _id: "9", city: "Lushnja", countryId: "1" },
  { _id: "10", city: "Pogradeci", countryId: "1" },
  { _id: "11", city: "Kavaja", countryId: "1" },
  { _id: "12", city: "Laçi", countryId: "1" },
  { _id: "13", city: "Lezha", countryId: "1" },
  { _id: "14", city: "Kukësi", countryId: "1" },
  { _id: "15", city: "Gjirokastra", countryId: "1" },
  { _id: "16", city: "Patosi", countryId: "1" },
  { _id: "17", city: "Kruja", countryId: "1" },
  { _id: "18", city: "Kuçova", countryId: "1" },
  { _id: "19", city: "Saranda", countryId: "1" },
  { _id: "20", city: "Peshkopia", countryId: "1" },
  { _id: "21", city: "Burreli", countryId: "1" },
  { _id: "22", city: "Cërriku", countryId: "1" },
  { _id: "23", city: "Çorovoda", countryId: "1" },
  { _id: "24", city: "Shijaku", countryId: "1" },
  { _id: "25", city: "Librazhdi", countryId: "1" },
  { _id: "26", city: "Tepelena", countryId: "1" },
  { _id: "27", city: "Gramshi", countryId: "1" },
  { _id: "28", city: "Poliçani", countryId: "1" },
  { _id: "29", city: "Bulqiza", countryId: "1" },
  { _id: "30", city: "Përmeti", countryId: "1" },
  { _id: "31", city: "Fushë-Kruja", countryId: "1" },
  { _id: "32", city: "Kamëza", countryId: "1" },
  { _id: "33", city: "Rrësheni", countryId: "1" },
  { _id: "34", city: "Ballshi", countryId: "1" },
  { _id: "35", city: "Mamurrasi", countryId: "1" },
  { _id: "36", city: "Bajram Curri", countryId: "1" },
  { _id: "37", city: "Erseka", countryId: "1" },
  { _id: "38", city: "Peqini", countryId: "1" },
  { _id: "39", city: "Divjaka", countryId: "1" },
  { _id: "40", city: "Selenica", countryId: "1" },
  { _id: "41", city: "Bilishti", countryId: "1" },
  { _id: "42", city: "Roskoveci", countryId: "1" },
  { _id: "43", city: "Këlcyra", countryId: "1" },
  { _id: "44", city: "Puka", countryId: "1" },
  { _id: "45", city: "Memaliaj", countryId: "1" },
  { _id: "46", city: "Rrogozhina", countryId: "1" },
  { _id: "47", city: "Ura Vajgurore", countryId: "1" },
  { _id: "48", city: "Himara", countryId: "1" },
  { _id: "49", city: "Delvina", countryId: "1" },
  { _id: "50", city: "Vora", countryId: "1" },
  { _id: "51", city: "Kopliku", countryId: "1" },
  { _id: "52", city: "Maliqi", countryId: "1" },
  { _id: "53", city: "Përrenjasi", countryId: "1" },
  { _id: "54", city: "Shtërmeni", countryId: "1" },
  { _id: "55", city: "Kruma", countryId: "1" },
  { _id: "56", city: "Libohova", countryId: "1" },
  { _id: "57", city: "Orikumi", countryId: "1" },
  { _id: "58", city: "Fushë-Arrëza", countryId: "1" },
  { _id: "59", city: "Shëngjini", countryId: "1" },
  { _id: "60", city: "Rubiku", countryId: "1" },
  { _id: "61", city: "Miloti", countryId: "1" },
  { _id: "62", city: "Leskoviku", countryId: "1" },
  { _id: "63", city: "Konispoli", countryId: "1" },
  { _id: "64", city: "Krasta", countryId: "1" },
  { _id: "65", city: "Kërraba", countryId: "1" },
  { _id: "66", city: "Përmeti", countryId: "1" },
  { _id: "67", city: "Skrapari", countryId: "1" },
  { _id: "68", city: "Tropoja", countryId: "1" },
];
export const zones = [
  { _id: "1", zone: "Kombinat", cityId: "1" },
  { _id: "2", zone: "Rruga e Kavajës", cityId: "1" },
  { _id: "3", zone: "Ali Demi", cityId: "1" },
  { _id: "4", zone: "Blloku", cityId: "1" },
  { _id: "5", zone: "Astiri", cityId: "1" },
  { _id: "6", zone: "Brryli", cityId: "1" },
  { _id: "7", zone: "Don Bosko", cityId: "1" },
  { _id: "8", zone: "Himarë", cityId: "1" },
  { _id: "9", zone: "Kamëz", cityId: "1" },
  { _id: "10", zone: "Paskuqan", cityId: "1" },
  { _id: "12", zone: "Komuna e Parisit", cityId: "1" },
  { _id: "13", zone: "Laprakë", cityId: "1" },
  { _id: "14", zone: "Kopshti Botanik", cityId: "1" },
  { _id: "15", zone: "Kopshti Zoologjik", cityId: "1" },
  { _id: "16", zone: "Liqeni i Thatë", cityId: "1" },
  { _id: "17", zone: "Rruga e Durrësit", cityId: "1" },
  { _id: "18", zone: "Stacioni i Trenit", cityId: "1" },
  { _id: "19", zone: "5 Maji", cityId: "1" },
  { _id: "20", zone: "Qyteti Studenti", cityId: "1" },
  { _id: "21", zone: "Sauk i Ri", cityId: "1" },
  { _id: "22", zone: "Sauk i Vjetër", cityId: "1" },
  { _id: "23", zone: "Rolling Hills", cityId: "1" },
  { _id: "24", zone: "Fresku", cityId: "1" },
  { _id: "25", zone: "Currila", cityId: "2" },
  { _id: "26", zone: "Gjiri i Lalëzit", cityId: "2" },
  { _id: "27", zone: "Golem", cityId: "2" },
  { _id: "28", zone: "Shkëmbi i Kavajës", cityId: "2" },
  { _id: "29", zone: "Plepa", cityId: "2" },
  { _id: "30", zone: "Qendër", cityId: "2" },
  { _id: "31", zone: "Zona Periferike", cityId: "2" },
  { _id: "32", zone: "Velipojë", cityId: "3" },
  { _id: "33", zone: "Shirokë", cityId: "3" },
  { _id: "34", zone: "Qendër", cityId: "3" },
  { _id: "35", zone: "Zona Periferike", cityId: "3" },
];
